version: '3.3'

services:
  api:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./httpd:/httpd
      - ./internal:/internal
    command: >
      sh -c "make dev"
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
