version: '3.3'

services:
  api:
    build:
      context: .
    container_name: go-api-c
    ports:
      - "8080:8080"
    volumes:
      - ./httpd:/httpd
      - ./internal:/internal
    command: >
      sh -c "make dev"
    depends_on:
      - db

  db:
    image: mongo
    container_name: mongodb-c
    ports:
      - "27017:27017"
