version: '3.3'

services:
  api:
    build:
      context: .
    ports:
      - '27017:27017'
    volumes:
      - ./httpd:/httpd
      - ./internal:/internal
    command: >
      sh -c "make dev"
    depends_on:
      - db

  db:
    image: mongo
